api/urls.py
from django.urls import path, re_path
from . import views


urlpatterns = [
    path('boards/', views.BoardListView.as_view(), name="board_list_api_view"),
    re_path(r'^board/(?P<pk>\w+)$', views.BoardView.as_view(), name="board_api_view"),
    re_path(r'^board/(?P<pk>\w+)/thread/(?P<tpk>[0-9]+)/comments', views.ThreadView.as_view(), name="thread_api_view"),
    re_path(r'^board/(?P<pk>\w+)/thread/(?P<tpk>[0-9]+)$', views.ThreadDetailView.as_view(), name="thread_detail_api_view")
]

boards/urls.py
from django.urls import path, re_path
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('lockdown', views.lockdown_all, name='lockdown'),    # ТОЛЬКО POST ЗАПРОСЫ
    path('pin',  views.pin_toggle, name="pin_thread_view"),   # ТОЛЬКО POST ЗАПРОСЫ
    re_path(r'^board/(?P<pk>\w+)$', views.ThreadListView.as_view(), name="board"),
    re_path(r'^board/(?P<pk>\w+)/new$', views.create_new_thread, name="create_thread"),
    re_path(r'^board/(?P<pk>\w+)/thread/(?P<tpk>[0-9]+)/comment$', views.add_comment_to_thread , name="add_comment_to_thread"),
    re_path(r'^board/(?P<pk>\w+)/thread/(?P<tpk>[0-9]+)$', views.ThreadDetailView.as_view(), name="thread_detail_view"),
]

handler404 = views.handler404

mkch/urls.py
from django.conf.urls.static import static
from django.conf import settings

from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView

from .views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('boards/', include('boards.urls')),
    path('captcha/', include('captcha.urls')),
    path('key/', include('keyauth.urls')),
    path('api/', include('api.urls')),
    path('passcode/', include('passcode.urls')),
    path('', RedirectView.as_view(url='/boards/', permanent=True)),
    path('settings/', settings_view, name="settings")
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

boards/models.py
import hashlib
import re
import statistics
import numpy as np

from django.core.validators import FileExtensionValidator
from django.utils.html import escape
from django.db import models

from passcode.models import Passcode

class Permission(models.Model):
    code = models.TextField(help_text="Код разрешения.")

    def __str__(self):
        return self.code

class Anon(models.Model):
    ip = models.GenericIPAddressField(unique=True)

    banned = models.BooleanField(default=False)

    passcodes = models.ManyToManyField(Passcode, blank=True)

    permissions = models.ManyToManyField(Permission, blank=True)

class Category(models.Model):
    name = models.TextField(help_text="Название Категории")

    def __str__(self):
        return self.name

class Board(models.Model):
    category = models.ForeignKey(Category, null=True, default=None, on_delete=models.SET_NULL)

    permissions_required = models.ManyToManyField(Permission, blank=True)

    code = models.CharField(max_length=20, help_text="Код доски (например, b)", primary_key=True)
    description = models.TextField(help_text="Короткое описание доски, которое пользователи видят в списке рядом с ней")
    detail_description = models.TextField(help_text="Подробное описание доски, видно которое пользователи видят в шапке самой доски", null=True)

    banner = models.FileField(help_text="Приветственный баннер", null=True, default=None)

    thread_limit = models.IntegerField(help_text="Количество тредов, при котором старые начнут удаляться, давая место новым (0 для неограниченного количества)", default=1000)
    bump_limit = models.IntegerField(help_text="Бамплимит. При достижении (бамплимит) комментариев в треде он 'утонет' (удалится) (0 для выключения бамплимита)", default=500)
    is_nsfw = models.BooleanField(help_text="Помечает борд как NSFW. Файлы с тредов в NSFW бордах отправляются МКБотом под спойлером, а сама категория помечается красным цветом.", default=False)
    enable_posting = models.BooleanField(help_text="Если False, разрешает постинг в борде только админам (борда всё ещё будет доступна для просмотра из списка)", default=True)
    lockdown = models.BooleanField(help_text="Карантин. В карантинных бордах НЕЛЬЗЯ создавать или бампать треды.", default=False)

    def __str__(self):
        return self.code

    def has_permission(self, anon):
        codes_a = [p.code for p in anon.permissions.all()]
        codes_b = [p.code for p in self.permissions_required.all()]

        for c in codes_b:
            if c not in codes_a:
                return False
        return True

class Thread(models.Model):
    class Meta:
        permissions = [
            ("create_new_threads", "Can create new threads"),
            ("comment_threads", "Can comment threads")
        ]

    creation = models.DateTimeField(help_text="Дата и время создания", auto_now=True)

    author = models.ForeignKey(Anon, help_text="Создатель треда", on_delete=models.SET_NULL, null=True)

    board = models.ForeignKey(Board, help_text="Доска треда", on_delete=models.SET_NULL, null=True)

    title = models.CharField(max_length=64, help_text="Заголовок", default="None")
    text = models.TextField(help_text="Текст")

    rating = models.IntegerField(default=0, help_text="Рейтинг треда. Он задаётся автоматически, крайне не рекомендуется менять вручную!!!")
    is_nsfw = models.BooleanField(help_text="Является ли тред NSFW (всегда True для комментов на NSFW бордах)", default=False)

    pinned = models.BooleanField(default=False, help_text="Если тред закреплён, он будет отображаться в самом начале списка тредов. Также можно задать из контектного меню треда если вы админ.")

    def rating_pp(self):
        l = [x.rating for x in Thread.objects.filter(board=self.board).exclude(id=self.id)]
        if len(l) == 0 and self.rating == 0:
            self.rating += 1
        elif len(l) > 0:
            highest = max(l)
            if self.rating <= highest:
                self.rating += 1

    def __str__(self):
        return str(self.id)

class Comment(models.Model):
    creation = models.DateTimeField(help_text="Дата и время создания", auto_now=True)

    thread = models.ForeignKey(Thread, help_text="Тред, к которому пишется комментарий", on_delete=models.SET_NULL, null=True)

    author = models.ForeignKey(Anon, help_text="Создатель треда", on_delete=models.SET_NULL, null=True)
    author_code = models.TextField(help_text="Код автора, задаётся автоматически.", null=True, default=None)
    is_nsfw = models.BooleanField(help_text="Является ли коммент NSFW (всегда True для комментов под NSFW тредами)", default=False)

    text = models.TextField(help_text="Текст")

    def formatted(self):
        t = escape(self.text) # как же мне похуй
        words = t.split(" ")
        for i, word in enumerate(words):
            if word.startswith("#"):
                word = word[1:]
                try:
                    _ = int(word)
                except Exception:
                    continue
                words[i] = f"<a href='#comment_{word}'>#{word}</a>"
            elif word.startswith("mkchtlnk"):
                parts = word.split(":")
                if len(parts) < 3:
                    continue
                board = parts[1]
                tid = parts[2]

                try:
                    _ = int(tid)
                    b = Board.objects.get(code=board)
                    thread = Thread.objects.get(board=b, id=tid)
                except Exception as e:
                    continue

                words[i] = f"<a href='/boards/board/{board}/thread/{tid}'>{board}->{tid}</a>"
        return " ".join(words)

    def replies(self):
        return Comment.objects.filter(thread=self.thread).filter(text__contains="#"+str(self.id))

    def __str__(self):
        return str(self.thread.id) + ", " + str(self.id)

class ThreadFile(models.Model):
    thread = models.ForeignKey(Thread, help_text="Тред, которому принадлежит файл", on_delete=models.SET_NULL, null=True)

    ftypes = {
        'photo': ['png', 'jpg', 'jpeg', 'webp', 'gif'],
        'video': ['mp4', 'webm']
    }
    allowed = ['png', 'jpg', 'jpeg', 'webp', 'mp4', 'webm', 'gif']

    file = models.FileField(help_text="Файл", null=True, validators=[FileExtensionValidator(allowed)])

    def fclass(self):
        p = self.file.path.split('.')[-1]
        for k, v in self.ftypes.items():
            if p in v:
                return k
        return "document"

    def type(self):
        return self.file.path.split('.')[-1]

class CommentFile(models.Model):
    comment = models.ForeignKey(Comment, help_text="Коммент, которому принадлежит файл", on_delete=models.SET_NULL, null=True)

    ftypes = {
        'photo': ['png', 'jpg', 'jpeg', 'webp', 'gif'],
        'video': ['mp4', 'webm']
    }
    allowed = ['png', 'jpg', 'jpeg', 'webp', 'mp4', 'webm', 'gif']

    file = models.FileField(help_text="Файл", null=True, validators=[FileExtensionValidator(allowed)])

    def fclass(self):
        p = self.file.path.split('.')[-1]
        for k, v in self.ftypes.items():
            if p in v:
                return k
        return "document"

    def type(self):
        return self.file.path.split('.')[-1]

boards/forms.py
from django.core.validators import FileExtensionValidator
from django.core import validators
from django.conf import settings
from django import forms

from captcha.fields import CaptchaField

class MultipleFileInput(forms.ClearableFileInput):
    allow_multiple_selected = True

class FileAllowedField(forms.FileField):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    default_validators = [FileExtensionValidator(['pdf'])]

class MultipleFileField(FileAllowedField):
    def __init__(self, *args, **kwargs):
        kwargs.setdefault("widget", MultipleFileInput(attrs={"ondrop": "drop_handler(event)", "ondragenter": "dragenter_handler(event)", "ondragleave": "dragleave_handler(event)", "ondragover": "dragover_handler(event)", "accept": ', '.join(settings.VALID_FILETYPES)}))

        super().__init__(*args, **kwargs)

    def clean(self, data, initial=None):
        single_file_clean = super().clean

        if isinstance(data, (list, tuple)):
            result = [single_file_clean(x, initial) for x in data]
        else:
            result = [single_file_clean(data, initial)]
        return result

# Хуёво реализованы формы, в интернете DRY-решения не нашёл. Если кто знает - кидайте PR

class FileValidationForm(forms.Form):
    files = MultipleFileField(required=False)

    def is_valid(self, request=None):
        if request:
            for f in request.FILES.getlist("files"):
                print(f)
                if not f.name.split(".")[-1] in settings.VALID_FILETYPES:
                    return False

        return super(FileValidationForm, self).is_valid()

class LockDownForm(forms.Form):
    lock = forms.BooleanField()

class NewThreadFormP(FileValidationForm):
    title = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Заголовок'}), min_length=1, max_length=64)
    text = forms.CharField(widget=forms.Textarea(attrs={'placeholder': 'Текст'}), max_length=16384)
    is_nsfw = forms.BooleanField(label="NSFW?", required=False)

class ThreadCommentFormP(FileValidationForm):
    text = forms.CharField(widget=forms.Textarea(attrs={'placeholder': 'Текст'}), max_length=16384)
    is_nsfw = forms.BooleanField(label="NSFW?", required=False)

class NewThreadForm(NewThreadFormP):
    captcha = CaptchaField()

class ThreadCommentForm(ThreadCommentFormP):
    captcha = CaptchaField()

boards/templates/boards/add_comment_to_thread.html
{% extends "base.html" %}

{% block title %}<title>mkch - Комментирование</title>{% endblock %}

{% block body %}
	<div class="container">
		<div class="thread">
			<h2>Добавить комментарий к треду</h2>
			{% if error %}
				<h3>{{error}}</h3>
			{% endif %}

			<form enctype="multipart/form-data" action="" method="post">
				{% csrf_token %}
				<table>
					{{form}}
				</table>
				<input type="submit" value="Создать" />
			</form>
		</div>
	</div>

	{% load static %}
	<script src="{% static 'js/dragNDrop.js' %}"></script>
{% endblock %}

boards/templates/boards/create_new_thread.html
{% extends "base.html" %}

{% block title %}<title>mkch - Создание треда</title>{% endblock %}

{% block body %}
	<div class="container">
		<div class="thread">
			<h2>Начать новый тред</h2>
			{% if error %}
				<h3>{{error}}</h3>
			{% endif %}
			<form enctype="multipart/form-data" action="" method="post">
				{% csrf_token %}
				<table>
					<h5>(DragNDrop supported)</h5>
					{{form}}
				</table>
				<input type="submit" value="Создать" />
			</form>
		</div>
	</div>

	{% load static %}
	<script src="{% static 'js/dragNDrop.js' %}"></script>
{% endblock %}

boards/templates/boards/thread_detail.html
{% extends "base.html" %}

{% block title %}<title>mkch - #{{thread.id}}</title>{% endblock %}

{% block body %}
    <div class="container" id="all-container">
        <div class="thread-container">
            <div class="thread-item">
                <div class="thread-file" id="thread-file">
                    {% for file in thread.threadfile_set.all %}
                        {% if file.fclass == "photo" %}
                            <img src="{{file.file.url}}" class="thread-image" id="img_thread_{{thread.id}}_{{forloop.counter}}" onclick="createImageFloatingDiv('img_thread_{{thread.id}}_{{forloop.counter}}')"></img>
                        {% elif file.fclass == "video" %}
                            <video controls="" src="{{file.file.url}}"></video>
                        {% else %}
                            <a href="{{file.file.url}}">{{file.file.name}}</a>
                        {% endif %}
                    {% endfor %}
                </div>

                <div class="thread-header">
                    <h1>{{thread.title}} </h1> <h5>{{thread.creation | date}}, {{thread.comment_set.count}} СМС, {{thread.rating}}PP</h5>
                </div>


                <div class="thread-description">
                    <h2>{{thread.text}}</h2>
                </div>
            </div>
                <div id="posts" class="posts-container">
                <div id="posts-inner" class="posts-inner-c">
                    {% for comment in thread.comment_set.all %}
                        <div class="post" id="post-{{comment.id}}">
                            <div class="post-header" id="comment_{{comment.id}}">
                                <h4>{% if thread.author == comment.author %}(ОП){% endif %} {{comment.author_code}} #{{comment.id}} {{comment.creation | date}}</h4>
                                    {% for file in comment.commentfile_set.all %}
                                                                {% if file.fclass == "photo" %}
                                                                    <img src="{{file.file.url}}" class="post-image{% if comment.is_nsfw and blur %}-nsfw{% endif %}" id="img_comment_{{comment.id}}_{{forloop.counter}}" onclick="createImageFloatingDiv('img_comment_{{comment.id}}_{{forloop.counter}}')"></img>
                                                                {% elif file.fclass == "video" %}
                                                                    <video class="video-post-{{comment.id}}" controls="" src="{{file.file.url}}"></video>
                                                                {% else %}
                                                                    <a href="{{file.file.url}}">{{file.file.name}}</a>
                                                                {% endif %}
                                    {% endfor %}
                                <div class="post-message"><h3>{{comment.formatted | safe}}</h3></div>
                            </div>

                            {% if comment.replies %}
                            <div class="replies">
                                <h6 class="reply">
                                    {% for reply in comment.replies %}
                                        <a href="#comment_{{reply.id}}">>> {{reply.id}}</a>
                                    {% endfor %}
                                </h6>
                            </div>
                            {% endif %}

                        </div>
                    {% endfor %}
                </div>
                {% if not thread.board.lockdown and thread.board.enable_posting or user.is_admin %}<a href="/boards/board/{{thread.board.code}}/thread/{{thread.id}}/comment" class="send-btn">Написать комментарий</a>{% endif %}
        </div>
    </div>

	{% load static %}
	<script src="{% static 'js/draggable.js' %}"></script>

	<script>
		function updateCommentList() {
			fetch(window.location.href)
				.then(response => response.text())
				.then(text => {
					const parser = new DOMParser();
					const list = parser.parseFromString(text, 'text/html');

					const posts = list.querySelectorAll(".post");
					const posts_o = document.querySelectorAll(".post");
					const container = document.querySelector(".posts-inner-c");

					if(posts.length <= posts_o.length) {return;}
					const diff = posts.length - posts_o.length;
                    for(let i = posts_o.length-1; i < posts.length; i++) {
                        container.appendChild(posts[i]);
					}
				});
		}

		setInterval(updateCommentList, 10000);
	</script>

{% endblock %}

boards/templates/boards/thread_list.html
{% extends "base.html" %}

{% block title %}<title>mkch - {{board.code}}</title>{% endblock %}

{% block body %}
	<div class="container">
		<form class="search-form">
			<input id="search" name="title" placeholder="Поиск..." type="text"></input>
			<input type="submit" value="Искать" />
		</form>
		<div class="board-container">
			{% if board.banner %}
				<div class="board-banner">
					<img src="{{board.banner.url}}" class="banner-image"></img>
				</div>
			{% endif %}

			{% if board.detail_description %}
				<h3 class="description">{{board.detail_description}}</h3>
			{% endif %}

		<div class="new-thread-button">
			{% if user.is_staff or not board.lockdown and board.enable_posting %}
				<a href="/boards/board/{{board.code}}/new">> начать тред <</a>
			{% endif %}
		</div>

		<div class="pagination">
			<span class="step-links">
				{% if page_obj.has_previous %}
					<a href="?page=1">&laquo; В начало</a>
					<a href="?page={{ page_obj.previous_page_number }}">Назад</a>
				{% endif %}

				<span class="current">
					Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}.
				</span>

				{% if page_obj.has_next %}
					<a href="?page={{ page_obj.next_page_number }}">Далее</a>
					<a href="?page={{ page_obj.paginator.num_pages }}">В конец &raquo;</a>
				{% endif %}
			</span>
		</div>
			<div id="thread-list">
				{% for thread in thread_list %}
					<div class="thread-container">
						<div class="thread-item">
							<div class="thread-file" onclick="">
							{% for file in thread.threadfile_set.all %}
									{% if file.fclass == "photo" %}
										<img src="{{file.file.url}}" id={{file.file.url}} class="thread-image" onclick="createImageFloatingDiv('{{file.file.url}}')"></img>
									{% elif file.fclass == "video" %}
										<video controls="" src="{{file.file.url}}"></video>
									{% else %}
										<a href="{{file.file.url}}">{{file.file.name}}</a>
									{% endif %}
							{% endfor %}
							</div>

							<div class="thread-header">
								<div onclick="window.location.href='/boards/board/{{board.code}}/thread/{{thread.id}}'"><h1>{{thread.title}}</h1> <h2>{{thread.comment_set.count}} СМС, {{thread.rating}}PP {{thread.creation | date}}</h2></div>
								{% if user.is_staff %}
									{% load static %}
									<img class="small-icon" src="{% if thread.pinned %}{% static 'media/unpin.png' %}{% else %}{% static 'media/pin.png' %}{% endif %}" onclick="pin({{thread.id}})"></img>
								{% endif %}
							</div>

							<div class="thread-description" onclick="window.location.href='/boards/board/{{board.code}}/thread/{{thread.id}}'">
								<h2>{{thread.text}}</h2>
							</div>
						</div>
					</div>
				{% endfor %}
			</div>
		</div>
	</div>

	<script src=" https://cdn.jsdelivr.net/npm/js-cookie@3.0.5/dist/js.cookie.min.js "></script>

	{% load static %}
	<script src="{% static 'js/draggable.js' %}"></script>

	<script>
		async function pin(id) {
		await fetch("/boards/pin", {
			method: "POST",
			credentials: "include",
			headers: {'X-CSRFToken': Cookies.get("csrftoken")},
			body: JSON.stringify({
			id: id,
			next: window.location.href
			})
		});
		window.location.reload();
		}
	</script>
{% endblock %}